const A=window.allinone;let settings=null,history=[],step=0;
const steps=[{title:"Welcome to ALLINONE",html:"A local-first AI workspace built to keep your projects, chats, and settings together.",button:"Get started"},{title:"What should we call you?",html:'<label>Your display name<input id="wizardName" maxlength="40" placeholder="Your name"></label>',button:"Continue"},{title:"Choose your safety setting",html:'<label class="option"><input id="wizardSafe" type="checkbox" checked><span><b>Safe Mode</b><small>Keep ALLINONE focused on safe, age-appropriate use.</small></span></label>',button:"Continue"},{title:"You're ready",html:"Your workspace is set up. The first release starts in Demo Mode while the local AI engine is being built.",button:"Open ALLINONE"}];
const $=id=>document.getElementById(id);
function renderStep(){const s=steps[step];$("step").innerHTML="<h1>"+s.title+"</h1><p>"+s.html+"</p>";if(step===1){const n=$("wizardName");n.value=settings&&settings.name||"";setTimeout(()=>n.focus(),0)}if(step===2)$("wizardSafe").checked=!settings||settings.safeMode!==false;$("back").style.visibility=step?"visible":"hidden";$("next").textContent=s.button;$("progress").style.width=((step+1)/steps.length*100)+"%"}
function openApp(){$("setup").classList.add("hidden");$("app").classList.remove("hidden");loadMain()}
async function boot(){settings=await A.getSettings();history=await A.getHistory();if(!settings){settings={name:"",safeMode:true,aiMode:"Demo Mode"};$("setup").classList.remove("hidden");renderStep()}else openApp()}
$("next").addEventListener("click",async()=>{if(step===1)settings.name=$("wizardName").value.trim()||"User";if(step===2)settings.safeMode=$("wizardSafe").checked;if(step<steps.length-1){step++;renderStep()}else{await A.saveSettings(settings);openApp()}});
$("back").addEventListener("click",()=>{if(step){step--;renderStep()}});
function addMessage(role,text){const row=document.createElement("div");row.className="msg "+role;row.innerHTML=(role==="ai"?'<span class="avatar">A</span>':"")+'<div class="bubble"></div>';row.querySelector(".bubble").textContent=text;$("messages").appendChild(row)}
function demoReply(text){const t=text.toLowerCase();if(t.includes("code"))return"Absolutely. Tell me what you want to build and I can help break it into small, testable pieces. In this release, the AI engine is still Demo Mode.";if(t.includes("project"))return"Let's turn that idea into a project: goal → features → files → milestones → tests. ALLINONE can keep that structure locally.";return"I’m ALLINONE’s Demo Mode right now. Your message was saved locally. The next milestone is connecting a real local model without requiring an API key."}
async function send(text){text=text.trim();if(!text)return;addMessage("user",text);history.push({role:"user",text});await A.saveHistory(history);$("status").textContent="Thinking…";setTimeout(async()=>{const reply=demoReply(text);addMessage("ai",reply);history.push({role:"ai",text:reply});await A.saveHistory(history);$("status").textContent="Ready"},350)}
$("composer").addEventListener("submit",e=>{e.preventDefault();const i=$("input");send(i.value);i.value=""});document.querySelectorAll(".quick button").forEach(b=>b.addEventListener("click",()=>send(b.dataset.prompt)));
$("newChat").addEventListener("click",async()=>{history=[];await A.saveHistory([]);$("messages").innerHTML="";welcome()});
function welcome(){addMessage("ai",settings&&settings.name?"Hey "+settings.name+"! I’m ALLINONE. What are we building today?":"Hey! I’m ALLINONE. What are we building today?")}
function loadMain(){$("modeLabel").textContent=settings.aiMode||"Local-first";$("nameSetting").value=settings.name||"";$("safeSetting").checked=settings.safeMode!==false;$("aiSetting").value=settings.aiMode||"Demo Mode";$("messages").innerHTML="";history.forEach(m=>addMessage(m.role==="user"?"user":"ai",m.text));if(!history.length)welcome()}
document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(b.dataset.page).classList.remove("hidden");$("pageTitle").textContent=b.querySelector("span")?b.querySelector("span").textContent:b.textContent.trim()}));
$("saveSettings").addEventListener("click",async()=>{settings={...settings,name:$("nameSetting").value.trim()||"User",safeMode:$("safeSetting").checked,aiMode:$("aiSetting").value};await A.saveSettings(settings);$("modeLabel").textContent=settings.aiMode;$("saved").textContent="Settings saved locally.";setTimeout(()=>$("saved").textContent="",1800)});
$("addProject").addEventListener("click",()=>{const name=prompt("Project name");if(!name||!name.trim())return;const card=document.createElement("article");card.className="project";card.innerHTML="<h3></h3><p>New local project</p>";card.querySelector("h3").textContent=name.trim();$("projectGrid").prepend(card)});boot();